#nullable enable

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.Text;
using TinyDispatcher.SourceGen.Generator;
using TinyDispatcher.SourceGen.Generator.Generation.Emitters.Pipelines;
using TinyDispatcher.SourceGen.Generator.Models;

namespace TinyDispatcher.SourceGen.Generator.Generation.Emitters.PipelineMaps;

internal static class PipelineMapAttributesEmitter
{
    public static void Emit(
        IGeneratorContext context,
        ImmutableArray<PipelineMapAttributeDescriptor> descriptors)
    {
        if (descriptors.IsDefaultOrEmpty)
        {
            return;
        }

        var writer = new CodeWriter(capacity: 8_000);

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();

        for (var i = 0; i < descriptors.Length; i++)
        {
            WriteAttribute(writer, descriptors[i]);
        }

        writer.EnsureAllBlocksClosed();
        context.AddSource(
            BuildHintName(descriptors[0]),
            SourceText.From(writer.ToString(), Encoding.UTF8));
    }

    private static void WriteAttribute(
        CodeWriter writer,
        PipelineMapAttributeDescriptor descriptor)
    {
        writer.Line("[assembly: global::TinyDispatcher.TinyDispatcherPipelineMapAttribute(");
        writer.Line($"    typeof({descriptor.PipelineTypeExpression}),");
        writer.Line($"    typeof({descriptor.ContextFullName}),");
        WriteTypeArray(writer, descriptor.CommandFullNames);
        WriteMiddlewareTypeArray(writer, descriptor.Middlewares);
        writer.Line($"    {descriptor.GlobalMiddlewareCount},");
        writer.Line($"    {BuildPolicyTypeExpression(descriptor.PolicyFullName)},");
        writer.Line($"    {descriptor.PolicyMiddlewareCount})]");
        writer.Line();
    }

    private static void WriteTypeArray(
        CodeWriter writer,
        ImmutableArray<string> typeNames)
    {
        writer.Line("    new System.Type[]");
        writer.BeginAnonymousBlock();

        for (var i = 0; i < typeNames.Length; i++)
        {
            writer.Line($"typeof({typeNames[i]}),");
        }

        writer.EndBlock(",");
    }

    private static void WriteMiddlewareTypeArray(
        CodeWriter writer,
        ImmutableArray<MiddlewareRef> middlewares)
    {
        writer.Line("    new System.Type[]");
        writer.BeginAnonymousBlock();

        for (var i = 0; i < middlewares.Length; i++)
        {
            writer.Line($"typeof({PipelineTypeNames.OpenGenericTypeof(middlewares[i])}),");
        }

        writer.EndBlock(",");
    }

    private static string BuildPolicyTypeExpression(string? policyFullName)
    {
        return policyFullName is null
            ? "null"
            : $"typeof({policyFullName})";
    }

    private static string BuildHintName(PipelineMapAttributeDescriptor descriptor)
    {
        return "PipelineMap.Attributes." +
            PipelineNameFactory.SanitizeTypeName(descriptor.ContextFullName) +
            ".g.cs";
    }
}
