using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.Text;
using TinyDispatcher.SourceGen.Generator;
using TinyDispatcher.SourceGen.Generator.Generation.Emitters.Pipelines;
using TinyDispatcher.SourceGen.Generator.Models;
using TinyDispatcher.SourceGen.Generator.Options;

namespace TinyDispatcher.SourceGen.Generator.Generation.Emitters;

internal sealed class EmptyPipelineContributionEmitter
{
    public void Emit(
        IGeneratorContext context,
        DiscoveryResult discovery,
        PipelineContributions contributions,
        GeneratorOptions options)
    {
        var w = new CodeWriter(capacity: 8_192);

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("using System;");
        w.Line("using Microsoft.Extensions.DependencyInjection;");
        w.Line();

        WriteAssemblyContributionAttributes(w, discovery, contributions, options);
        w.Line();

        w.BeginBlock($"namespace {options.GeneratedNamespace}");
        w.BeginBlock("internal static partial class ThisAssemblyContribution");

        w.BeginBlock("internal static global::TinyDispatcher.Bootstrap.AssemblyContribution Create()");
        w.Line("return new global::TinyDispatcher.Bootstrap.AssemblyContribution(");
        w.Line("    contextType: GetContextType(),");
        w.Line("    registerServices: AddServices,");
        w.Line("    handlers: GetHandlerBindings(),");
        w.Line("    pipelines: GetPipelineBindings(),");
        w.Line("    policies: GetPolicyBindings());");
        w.EndBlock();
        w.Line();

        w.BeginBlock("internal static void AddServices(IServiceCollection services)");
        w.Line("if (services is null) throw new ArgumentNullException(nameof(services));");
        w.Line();
        w.Line("AddGeneratedPipelines(services);");
        w.Line("AddGeneratedHandlers(services);");
        w.EndBlock();
        w.Line();

        w.Line($"private static System.Type? GetContextType() => {GetContextTypeExpression(options)};");
        w.Line();

        WriteHandlerBindings(w, discovery);
        w.Line();
        WritePipelineBindings(w, contributions);
        w.Line();
        WritePolicyBindings(w, contributions);
        w.Line();

        w.Line("static partial void AddGeneratedPipelines(IServiceCollection services);");
        w.Line("static partial void AddGeneratedHandlers(IServiceCollection services);");
        w.EndBlock();
        w.Line();

        w.BeginBlock("internal static partial class ThisAssemblyPipelineContribution");
        w.BeginBlock("internal static void Add(IServiceCollection services)");
        w.Line("ThisAssemblyContribution.AddServices(services);");
        w.EndBlock();
        w.EndBlock();
        w.EndBlock();

        w.EnsureAllBlocksClosed();
        context.AddSource("ThisAssemblyContribution.g.cs", SourceText.From(w.ToString(), Encoding.UTF8));
    }

    private static void WriteAssemblyContributionAttributes(
        CodeWriter w,
        DiscoveryResult discovery,
        PipelineContributions contributions,
        GeneratorOptions options)
    {
        if (!string.IsNullOrWhiteSpace(options.CommandContextType))
        {
            w.Line(
                $"[assembly: global::TinyDispatcher.TinyDispatcherAssemblyContextContributionAttribute(typeof({PipelineTypeNames.NormalizeFqn(options.CommandContextType!)}))]");
        }

        for (var i = 0; i < discovery.Commands.Length; i++)
        {
            var command = discovery.Commands[i];
            w.Line(
                $"[assembly: global::TinyDispatcher.TinyDispatcherHandlerContributionAttribute(typeof({command.MessageTypeFqn}), typeof({command.HandlerTypeFqn}), typeof({command.ContextTypeFqn}))]");
        }

        if (contributions.Globals.Length > 0)
        {
            w.Line(
                $"[assembly: global::TinyDispatcher.TinyDispatcherPipelineContributionAttribute(new System.Type[] {{ {BuildAttributeTypeList(contributions.Globals)} }})]");
        }

        var orderedCommands = PipelineOrdering.GetStringsInStableOrder(contributions.PerCommand.Keys);
        for (var i = 0; i < orderedCommands.Length; i++)
        {
            var command = orderedCommands[i];
            w.Line(
                $"[assembly: global::TinyDispatcher.TinyDispatcherPipelineContributionAttribute(new System.Type[] {{ {BuildAttributeTypeList(contributions.PerCommand[command])} }}, CommandType = typeof({command}))]");
        }

        for (var i = 0; i < contributions.Policies.Length; i++)
        {
            var policy = contributions.Policies[i];
            w.Line(
                $"[assembly: global::TinyDispatcher.TinyDispatcherPolicyContributionAttribute(typeof({policy.PolicyTypeFqn}), new System.Type[] {{ {BuildAttributeTypeList(policy.Middlewares)} }}, new System.Type[] {{ {BuildCommandTypeList(policy.Commands)} }})]");
        }
    }

    private static string GetContextTypeExpression(GeneratorOptions options)
    {
        if (string.IsNullOrWhiteSpace(options.CommandContextType))
            return "null";

        return $"typeof({PipelineTypeNames.NormalizeFqn(options.CommandContextType!)})";
    }

    private static void WriteHandlerBindings(CodeWriter w, DiscoveryResult discovery)
    {
        w.Line("private static System.Collections.Generic.IReadOnlyList<global::TinyDispatcher.Bootstrap.HandlerBinding> GetHandlerBindings()");

        if (discovery.Commands.Length == 0)
        {
            w.Line("    => System.Array.Empty<global::TinyDispatcher.Bootstrap.HandlerBinding>();");
            return;
        }

        w.Line("    => new global::TinyDispatcher.Bootstrap.HandlerBinding[]");
        w.BeginAnonymousBlock(string.Empty);

        for (var i = 0; i < discovery.Commands.Length; i++)
        {
            var command = discovery.Commands[i];
            w.Line(
                $"new(typeof({command.MessageTypeFqn}), typeof({command.HandlerTypeFqn}), typeof({command.ContextTypeFqn})),");
        }

        w.EndBlock();
        w.Line(";");
    }

    private static void WritePipelineBindings(CodeWriter w, PipelineContributions contributions)
    {
        w.Line("private static System.Collections.Generic.IReadOnlyList<global::TinyDispatcher.Bootstrap.PipelineBinding> GetPipelineBindings()");

        var orderedCommands = PipelineOrdering.GetStringsInStableOrder(contributions.PerCommand.Keys);
        var hasBindings = contributions.Globals.Length > 0 || orderedCommands.Length > 0;

        if (!hasBindings)
        {
            w.Line("    => System.Array.Empty<global::TinyDispatcher.Bootstrap.PipelineBinding>();");
            return;
        }

        w.Line("    => new global::TinyDispatcher.Bootstrap.PipelineBinding[]");
        w.BeginAnonymousBlock(string.Empty);

        if (contributions.Globals.Length > 0)
            w.Line($"new(commandType: null, middlewares: {BuildMiddlewareArray(contributions.Globals)}),");

        for (var i = 0; i < orderedCommands.Length; i++)
        {
            var command = orderedCommands[i];
            w.Line($"new(typeof({command}), {BuildMiddlewareArray(contributions.PerCommand[command])}),");
        }

        w.EndBlock();
        w.Line(";");
    }

    private static void WritePolicyBindings(CodeWriter w, PipelineContributions contributions)
    {
        w.Line("private static System.Collections.Generic.IReadOnlyList<global::TinyDispatcher.Bootstrap.PolicyBinding> GetPolicyBindings()");

        if (contributions.Policies.Length == 0)
        {
            w.Line("    => System.Array.Empty<global::TinyDispatcher.Bootstrap.PolicyBinding>();");
            return;
        }

        w.Line("    => new global::TinyDispatcher.Bootstrap.PolicyBinding[]");
        w.BeginAnonymousBlock(string.Empty);

        for (var i = 0; i < contributions.Policies.Length; i++)
        {
            var policy = contributions.Policies[i];
            w.Line(
                $"new(typeof({policy.PolicyTypeFqn}), {BuildMiddlewareArray(policy.Middlewares)}, {BuildPolicyCommandArray(policy.Commands)}),");
        }

        w.EndBlock();
        w.Line(";");
    }

    private static string BuildMiddlewareArray(IReadOnlyList<MiddlewareRef> middlewares)
    {
        if (middlewares.Count == 0)
            return "System.Array.Empty<global::TinyDispatcher.Bootstrap.MiddlewareBinding>()";

        var source = new StringBuilder();
        source.Append("new global::TinyDispatcher.Bootstrap.MiddlewareBinding[] { ");

        for (var i = 0; i < middlewares.Count; i++)
        {
            if (i > 0)
                source.Append(", ");

            source.Append("new(typeof(");
            source.Append(PipelineTypeNames.OpenGenericTypeof(middlewares[i]));
            source.Append("))");
        }

        source.Append(" }");
        return source.ToString();
    }

    private static string BuildPolicyCommandArray(ImmutableArray<string> commands)
    {
        if (commands.Length == 0)
            return "System.Array.Empty<global::TinyDispatcher.Bootstrap.PolicyCommandBinding>()";

        var source = new StringBuilder();
        source.Append("new global::TinyDispatcher.Bootstrap.PolicyCommandBinding[] { ");

        for (var i = 0; i < commands.Length; i++)
        {
            if (i > 0)
                source.Append(", ");

            source.Append("new(typeof(");
            source.Append(commands[i]);
            source.Append("))");
        }

        source.Append(" }");
        return source.ToString();
    }

    private static string BuildAttributeTypeList(IReadOnlyList<MiddlewareRef> middlewares)
    {
        if (middlewares.Count == 0)
            return string.Empty;

        var source = new StringBuilder();

        for (var i = 0; i < middlewares.Count; i++)
        {
            if (i > 0)
                source.Append(", ");

            source.Append("typeof(");
            source.Append(PipelineTypeNames.OpenGenericTypeof(middlewares[i]));
            source.Append(")");
        }

        return source.ToString();
    }

    private static string BuildCommandTypeList(ImmutableArray<string> commands)
    {
        if (commands.Length == 0)
            return string.Empty;

        var source = new StringBuilder();

        for (var i = 0; i < commands.Length; i++)
        {
            if (i > 0)
                source.Append(", ");

            source.Append("typeof(");
            source.Append(commands[i]);
            source.Append(")");
        }

        return source.ToString();
    }
}
