using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.Text;
using TinyDispatcher.SourceGen.Generator;
using TinyDispatcher.SourceGen.Generator.Generation;
using TinyDispatcher.SourceGen.Generator.Generation.Emitters.Pipelines;
using TinyDispatcher.SourceGen.Generator.Models;
using TinyDispatcher.SourceGen.Generator.Options;

namespace TinyDispatcher.SourceGen.Generator.Generation.Emitters;

internal sealed class ThisAssemblyContributionEmitter
{
    public void Emit(
        IGeneratorContext context,
        DiscoveryResult discovery,
        PipelineContributions contributions,
        GeneratorOptions options,
        ImmutableArray<string> pipelineRegistrationMethodNames = default,
        ImmutableArray<PipelineContributionSource> contributionSources = default)
    {
        var effectiveContributionSources = GetContributionSources(
            options,
            contributions,
            contributionSources);
        var w = new CodeWriter(capacity: 8_192);

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("using System;");
        w.Line("using Microsoft.Extensions.DependencyInjection;");
        w.Line();

        WriteAssemblyContributionAttributes(w, discovery, effectiveContributionSources);
        w.Line();

        w.BeginBlock($"namespace {options.GeneratedNamespace}");
        w.BeginBlock("internal static partial class ThisAssemblyContribution");

        w.BeginBlock("internal static global::TinyDispatcher.Bootstrap.AssemblyContribution Create()");
        w.Line("return new global::TinyDispatcher.Bootstrap.AssemblyContribution(");
        w.Line("    registerServices: AddServices);");
        w.EndBlock();
        w.Line();

        w.BeginBlock("internal static void AddServices(IServiceCollection services)");
        w.Line("if (services is null) throw new ArgumentNullException(nameof(services));");
        w.Line();
        w.Line("AddGeneratedPipelines(services);");
        w.Line("AddGeneratedHandlers(services);");
        w.EndBlock();
        w.Line();

        WriteAddGeneratedPipelines(w, pipelineRegistrationMethodNames);
        w.Line("static partial void AddGeneratedHandlers(IServiceCollection services);");
        w.EndBlock();
        w.Line();

        w.EndBlock();

        w.EnsureAllBlocksClosed();
        context.AddSource("ThisAssemblyContribution.g.cs", SourceText.From(w.ToString(), Encoding.UTF8));
    }

    private static ImmutableArray<PipelineContributionSource> GetContributionSources(
        GeneratorOptions options,
        PipelineContributions contributions,
        ImmutableArray<PipelineContributionSource> contributionSources)
    {
        if (!contributionSources.IsDefaultOrEmpty)
        {
            return contributionSources;
        }

        return ImmutableArray.Create(new PipelineContributionSource(options, contributions));
    }

    private static void WriteAddGeneratedPipelines(
        CodeWriter w,
        ImmutableArray<string> methodNames)
    {
        w.BeginBlock("private static void AddGeneratedPipelines(IServiceCollection services)");

        if (!methodNames.IsDefaultOrEmpty)
        {
            for (var i = 0; i < methodNames.Length; i++)
            {
                w.Line($"{methodNames[i]}(services);");
            }
        }

        w.EndBlock();
    }

    private static void WriteAssemblyContributionAttributes(
        CodeWriter w,
        DiscoveryResult discovery,
        ImmutableArray<PipelineContributionSource> contributionSources)
    {
        var assemblyContextType = TryGetSingleContextType(contributionSources);
        if (!string.IsNullOrWhiteSpace(assemblyContextType))
        {
            w.Line(
                $"[assembly: global::TinyDispatcher.TinyDispatcherAssemblyContextContributionAttribute(typeof({PipelineTypeNames.NormalizeFqn(assemblyContextType!)}))]");
        }

        for (var i = 0; i < discovery.Commands.Length; i++)
        {
            var command = discovery.Commands[i];
            w.Line(
                $"[assembly: global::TinyDispatcher.TinyDispatcherHandlerContributionAttribute(typeof({command.MessageTypeFqn}), typeof({command.HandlerTypeFqn}), typeof({command.ContextTypeFqn}))]");
        }

        for (var i = 0; i < contributionSources.Length; i++)
        {
            var source = contributionSources[i];
            var contributions = source.Contributions;
            var options = source.Options;

            if (contributions.Globals.Length > 0)
            {
                w.Line(
                    $"[assembly: global::TinyDispatcher.TinyDispatcherPipelineContributionAttribute(new System.Type[] {{ {BuildAttributeTypeList(contributions.Globals)} }}{BuildContributionContextArgument(options)})]");
            }

            var orderedCommands = PipelineOrdering.GetStringsInStableOrder(contributions.PerCommand.Keys);
            for (var j = 0; j < orderedCommands.Length; j++)
            {
                var command = orderedCommands[j];
                w.Line(
                    $"[assembly: global::TinyDispatcher.TinyDispatcherPipelineContributionAttribute(new System.Type[] {{ {BuildAttributeTypeList(contributions.PerCommand[command])} }}, CommandType = typeof({command}){BuildContributionContextArgument(options)})]");
            }

            for (var j = 0; j < contributions.Policies.Length; j++)
            {
                var policy = contributions.Policies[j];
                w.Line(
                    $"[assembly: global::TinyDispatcher.TinyDispatcherPolicyContributionAttribute(typeof({policy.PolicyTypeFqn}), new System.Type[] {{ {BuildAttributeTypeList(policy.Middlewares)} }}, new System.Type[] {{ {BuildCommandTypeList(policy.Commands)} }}{BuildContributionContextArgument(options)})]");
            }
        }
    }

    private static string BuildContributionContextArgument(GeneratorOptions options)
    {
        if (string.IsNullOrWhiteSpace(options.CommandContextType))
        {
            return string.Empty;
        }

        return $", ContextType = typeof({PipelineTypeNames.NormalizeFqn(options.CommandContextType!)})";
    }

    private static string? TryGetSingleContextType(
        ImmutableArray<PipelineContributionSource> contributionSources)
    {
        string? contextType = null;

        for (var i = 0; i < contributionSources.Length; i++)
        {
            var nextContextType = contributionSources[i].Options.CommandContextType;
            if (string.IsNullOrWhiteSpace(nextContextType))
            {
                continue;
            }

            if (contextType is null)
            {
                contextType = nextContextType;
                continue;
            }

            if (!string.Equals(contextType, nextContextType, System.StringComparison.Ordinal))
            {
                return null;
            }
        }

        return contextType;
    }

    private static string BuildAttributeTypeList(IReadOnlyList<MiddlewareRef> middlewares)
    {
        if (middlewares.Count == 0)
            return string.Empty;

        var source = new StringBuilder();

        for (var i = 0; i < middlewares.Count; i++)
        {
            if (i > 0)
                source.Append(", ");

            source.Append("typeof(");
            source.Append(PipelineTypeNames.OpenGenericTypeof(middlewares[i]));
            source.Append(")");
        }

        return source.ToString();
    }

    private static string BuildCommandTypeList(ImmutableArray<string> commands)
    {
        if (commands.Length == 0)
            return string.Empty;

        var source = new StringBuilder();

        for (var i = 0; i < commands.Length; i++)
        {
            if (i > 0)
                source.Append(", ");

            source.Append("typeof(");
            source.Append(commands[i]);
            source.Append(")");
        }

        return source.ToString();
    }
}
