#nullable enable

using System.Text;
using Microsoft.CodeAnalysis.Text;

using TinyDispatcher.SourceGen.Generator;
using TinyDispatcher.SourceGen.Generator.Generation.Emitters.Pipelines;

namespace TinyDispatcher.SourceGen.Generator.Generation.Emitters.PipelineMaps;

internal static class PipelineMapJsonEmitter
{
    public static void Emit(IGeneratorContext context, PipelineDescriptor descriptor)
    {
        var source = WriteSource(descriptor);
        var hintName = BuildHintName(descriptor);

        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string WriteSource(PipelineDescriptor descriptor)
    {
        var writer = new CodeWriter(capacity: 8_000);

        WriteFileHeader(writer);
        WriteJsonPayload(writer, descriptor);
        writer.Line("*/");

        writer.EnsureAllBlocksClosed();
        return writer.ToString();
    }

    private static void WriteFileHeader(CodeWriter writer)
    {
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line("/*");
        writer.Line("TINYDISPATCHER_PIPELINE_MAP_JSON");
    }

    private static void WriteJsonPayload(CodeWriter writer, PipelineDescriptor descriptor)
    {
        writer.Line("{");
        writer.Line($"  \"command\": \"{Escape(descriptor.CommandFullName)}\",");
        writer.Line($"  \"context\": \"{Escape(descriptor.ContextFullName)}\",");
        writer.Line($"  \"handler\": \"{Escape(descriptor.HandlerFullName)}\",");
        WritePolicies(writer, descriptor);
        WriteMiddlewares(writer, descriptor);
        writer.Line("}");
    }

    private static void WritePolicies(CodeWriter writer, PipelineDescriptor descriptor)
    {
        writer.Line("  \"policies\": [");
        for (var i = 0; i < descriptor.PoliciesApplied.Count; i++)
        {
            var comma = i == descriptor.PoliciesApplied.Count - 1 ? "" : ",";
            writer.Line($"    \"{Escape(descriptor.PoliciesApplied[i])}\"{comma}");
        }

        writer.Line("  ],");
    }

    private static void WriteMiddlewares(CodeWriter writer, PipelineDescriptor descriptor)
    {
        writer.Line("  \"middlewares\": [");
        for (var i = 0; i < descriptor.Middlewares.Count; i++)
        {
            var middleware = descriptor.Middlewares[i];
            var comma = i == descriptor.Middlewares.Count - 1 ? "" : ",";

            writer.Line("    {");
            writer.Line($"      \"type\": \"{Escape(middleware.MiddlewareFullName)}\",");
            writer.Line($"      \"source\": \"{Escape(middleware.Source)}\"");
            writer.Line($"    }}{comma}");
        }

        writer.Line("  ]");
    }

    private static string BuildHintName(PipelineDescriptor descriptor)
    {
        return "PipelineMap." +
            PipelineNameFactory.SanitizeTypeName(descriptor.ContextFullName) +
            "." +
            PipelineNameFactory.SanitizeTypeName(descriptor.CommandFullName) +
            ".g.cs";
    }

    private static string Escape(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}

