#nullable enable

using System.Text;
using Microsoft.CodeAnalysis.Text;
using TinyDispatcher.SourceGen.Abstractions;

namespace TinyDispatcher.SourceGen.Emitters.PipelineMaps;

internal static class PipelineMapJsonEmitter
{
    public static void Emit(IGeneratorContext context, PipelineDescriptor d)
    {
        var w = new CodeWriter(capacity: 8_000);

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("/*");
        w.Line("TINYDISPATCHER_PIPELINE_MAP_JSON");

        // JSON payload (kept stable + readable)
        w.Line("{");
        w.Line($"  \"command\": \"{Escape(d.CommandFullName)}\",");
        w.Line($"  \"context\": \"{Escape(d.ContextFullName)}\",");
        w.Line($"  \"handler\": \"{Escape(d.HandlerFullName)}\",");
        w.Line("  \"policies\": [");

        for (var i = 0; i < d.PoliciesApplied.Count; i++)
        {
            var comma = i == d.PoliciesApplied.Count - 1 ? "" : ",";
            w.Line($"    \"{Escape(d.PoliciesApplied[i])}\"{comma}");
        }

        w.Line("  ],");
        w.Line("  \"middlewares\": [");

        for (var i = 0; i < d.Middlewares.Count; i++)
        {
            var mw = d.Middlewares[i];
            var comma = i == d.Middlewares.Count - 1 ? "" : ",";

            w.Line("    {");
            w.Line($"      \"type\": \"{Escape(mw.MiddlewareFullName)}\",");
            w.Line($"      \"source\": \"{Escape(mw.Source)}\"");
            w.Line($"    }}{comma}");
        }

        w.Line("  ]");
        w.Line("}");
        w.Line("*/");

        w.EnsureAllBlocksClosed();

        var hint = $"PipelineMap.{Sanitize(d.CommandFullName)}.g.cs";
        context.AddSource(hint, SourceText.From(w.ToString(), Encoding.UTF8));
    }

    private static string Sanitize(string s)
        => s.Replace("global::", "")
            .Replace('.', '_')
            .Replace('+', '_');

    private static string Escape(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}