#nullable enable

using System;
using System.Text;
using Microsoft.CodeAnalysis.Text;
using TinyDispatcher.SourceGen.Abstractions;

namespace TinyDispatcher.SourceGen.Emitters.PipelineMaps;

internal static class PipelineMapJsonEmitter
{
    public static void Emit(IGeneratorContext context, PipelineDescriptor d)
    {
        var sb = new StringBuilder(4_000);

        sb.AppendLine("{");
        sb.AppendLine($"  \"command\": \"{Escape(d.CommandFullName)}\",");
        sb.AppendLine($"  \"context\": \"{Escape(d.ContextFullName)}\",");
        sb.AppendLine($"  \"handler\": \"{Escape(d.HandlerFullName)}\",");
        sb.AppendLine("  \"policies\": [");

        for (var i = 0; i < d.PoliciesApplied.Count; i++)
        {
            var comma = i == d.PoliciesApplied.Count - 1 ? "" : ",";
            sb.AppendLine($"    \"{Escape(d.PoliciesApplied[i])}\"{comma}");
        }

        sb.AppendLine("  ],");
        sb.AppendLine("  \"middlewares\": [");

        for (var i = 0; i < d.Middlewares.Count; i++)
        {
            var mw = d.Middlewares[i];
            var comma = i == d.Middlewares.Count - 1 ? "" : ",";

            sb.AppendLine("    {");
            sb.AppendLine($"      \"type\": \"{Escape(mw.MiddlewareFullName)}\",");
            sb.AppendLine($"      \"source\": \"{Escape(mw.Source)}\"");
            sb.AppendLine($"    }}{comma}");
        }

        sb.AppendLine("  ]");
        sb.AppendLine("}");

        var hint = $"PipelineMap.{Sanitize(d.CommandFullName)}.g.cs";

        var content =
            "// <auto-generated/>\n" +
            "#nullable enable\n" +
            "/*\n" +
            "TINYDISPATCHER_PIPELINE_MAP_JSON\n" +
            sb.ToString() +
            "\n*/\n";

        context.AddSource(hint, SourceText.From(content, Encoding.UTF8));
    }

    private static string Sanitize(string s)
        => s.Replace("global::", "")
            .Replace('.', '_')
            .Replace('+', '_');

    private static string Escape(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
