// TinyDispatcher.SourceGen/ContributionEmitter.cs
using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis.Text;
using TinyDispatcher.SourceGen.Abstractions;
using TinyDispatcher.SourceGen.Internal;

namespace TinyDispatcher.SourceGen;

public sealed class ContributionEmitter : ICodeEmitter
{
    public void Emit(IGeneratorContext context, DiscoveryResult result, GeneratorOptions options)
    {
        if (result.Commands.Length == 0 && result.Queries.Length == 0)
            return;

        var source = BuildSource(result, options);

        context.AddSource(
            hintName: "ThisAssemblyContribution.g.cs",
            sourceText: SourceText.From(source, Encoding.UTF8));
    }

    private static string BuildSource(DiscoveryResult result, GeneratorOptions options)
    {
        var sb = new IndentedStringBuilder();
        var core = $"global::{Known.CoreNamespace}";

        sb.AppendLine("// <auto-generated/>")
          .AppendLine("using System;")
          .AppendLine("using System.Collections.Generic;")
          .AppendLine()
          .AppendLine($"namespace {options.GeneratedNamespace}")
          .AppendLine("{")
          .Indent();

        sb.AppendLine($"internal sealed class ThisAssemblyContribution : {core}.IMapContribution")
          .AppendLine("{")
          .Indent();

        AppendCommandHandlersProperty(sb, result);
        sb.AppendLine();
        AppendQueryHandlersProperty(sb, result);

        sb.Unindent()
          .AppendLine("}")
          .Unindent()
          .AppendLine("}");

        return sb.ToString();
    }

    private static void AppendCommandHandlersProperty(IndentedStringBuilder sb, DiscoveryResult result)
    {
        if (result.Commands.Length == 0)
        {
            sb.AppendLine("public IEnumerable<KeyValuePair<Type, Type>> CommandHandlers { get; } =")
              .AppendLine("    Array.Empty<KeyValuePair<Type, Type>>();");
            return;
        }

        sb.AppendLine("public IEnumerable<KeyValuePair<Type, Type>> CommandHandlers { get; } = new KeyValuePair<Type, Type>[]")
          .AppendLine("{")
          .Indent();

        for (var i = 0; i < result.Commands.Length; i++)
        {
            var contract = result.Commands[i];
            var comma = i == result.Commands.Length - 1 ? string.Empty : ",";

            sb.AppendLine($"new KeyValuePair<Type, Type>(typeof({contract.MessageTypeFqn}), typeof({contract.HandlerTypeFqn})){comma}");
        }

        sb.Unindent()
          .AppendLine("};");
    }

    private static void AppendQueryHandlersProperty(IndentedStringBuilder sb, DiscoveryResult result)
    {
        if (result.Queries.Length == 0)
        {
            sb.AppendLine("public IEnumerable<KeyValuePair<Type, Type>> QueryHandlers { get; } =")
              .AppendLine("    Array.Empty<KeyValuePair<Type, Type>>();");
            return;
        }

        sb.AppendLine("public IEnumerable<KeyValuePair<Type, Type>> QueryHandlers { get; } = new KeyValuePair<Type, Type>[]")
          .AppendLine("{")
          .Indent();

        for (var i = 0; i < result.Queries.Length; i++)
        {
            var contract = result.Queries[i];
            var comma = i == result.Queries.Length - 1 ? string.Empty : ",";

            sb.AppendLine($"new KeyValuePair<Type, Type>(typeof({contract.QueryTypeFqn}), typeof({contract.HandlerTypeFqn})){comma}");
        }

        sb.Unindent()
          .AppendLine("};");
    }
}
