// FILE: src/TinyDispatcher.SourceGen/EmptyPipelineEmmiter.cs
// Replace the current emitter implementation with this version.
// It generates a partial class that ALWAYS exists and calls both:
// - AddGeneratedPipelines(...)  (generated by PipelineCodeEmitter when applicable)
// - AddGeneratedHandlers(...)   (generated by the new HandlersRegistrationEmitter)

using System.Text;
using Microsoft.CodeAnalysis.Text;
using TinyDispatcher.SourceGen.Abstractions;
using TinyDispatcher.SourceGen.Generator.Models;

namespace TinyDispatcher.SourceGen;

internal sealed class EmptyPipelineContributionEmitter : ICodeEmitter
{
    public void Emit(IGeneratorContext context, DiscoveryResult result, GeneratorOptions options)
    {
        var ns = options.GeneratedNamespace;

        var source = $$"""
        // <auto-generated/>
        #nullable enable
        using System;
        using Microsoft.Extensions.DependencyInjection;

        namespace {{ns}}
        {
          internal static partial class ThisAssemblyPipelineContribution
          {
            internal static void Add(IServiceCollection services)
            {
              if (services is null) throw new ArgumentNullException(nameof(services));

              AddGeneratedPipelines(services);
              AddGeneratedHandlers(services);
            }

            static partial void AddGeneratedPipelines(IServiceCollection services);
            static partial void AddGeneratedHandlers(IServiceCollection services);
          }
        }
        """;

        context.AddSource("ThisAssemblyPipelineContribution.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}
