using System.Text;
using Microsoft.CodeAnalysis.Text;
using TinyDispatcher.SourceGen.Generator.Models;

using TinyDispatcher.SourceGen.Generator;
using TinyDispatcher.SourceGen.Generator.Options;

namespace TinyDispatcher.SourceGen;

internal sealed class EmptyPipelineContributionEmitter
{
    public void Emit(IGeneratorContext context, GeneratorOptions options)
    {
        var ns = options.GeneratedNamespace;

        var source = $$"""
        // <auto-generated/>
        #nullable enable
        using System;
        using Microsoft.Extensions.DependencyInjection;

        namespace {{ns}}
        {
          internal static partial class ThisAssemblyPipelineContribution
          {
            internal static void Add(IServiceCollection services)
            {
              if (services is null) throw new ArgumentNullException(nameof(services));

              AddGeneratedPipelines(services);
              AddGeneratedHandlers(services);
            }

            static partial void AddGeneratedPipelines(IServiceCollection services);
            static partial void AddGeneratedHandlers(IServiceCollection services);
          }
        }
        """;

        context.AddSource("ThisAssemblyPipelineContribution.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}
