// TinyDispatcher.SourceGen/ModuleInitializerEmitter.cs
using System.Text;
using Microsoft.CodeAnalysis.Text;
using TinyDispatcher.SourceGen.Abstractions;

namespace TinyDispatcher.SourceGen;

public sealed class ModuleInitializerEmitter : ICodeEmitter
{
    public void Emit(IGeneratorContext context, DiscoveryResult result, GeneratorOptions options)
    {
        if (result.Commands.Length == 0 && result.Queries.Length == 0)
            return;

        var ns = options.GeneratedNamespace;
        var core = Known.CoreNamespace;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("  internal static class DispatcherModuleInitializer");
        sb.AppendLine("  {");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Init()");
        sb.AppendLine("    {");
        sb.AppendLine("      // Contribute this assembly's maps");
        sb.AppendLine($"      global::{core}.DispatcherBootstrap.AddContribution(new ThisAssemblyContribution());");
        sb.AppendLine();
        sb.AppendLine("      // Contribute this assembly's pipeline registrations (safe: contributor always exists)");
        sb.AppendLine($"      global::{core}.DispatcherPipelineBootstrap.AddContribution(");
        sb.AppendLine($"        services => global::{ns}.ThisAssemblyPipelineContribution.Add(services));");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");

        context.AddSource(
            "DispatcherModuleInitializer.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
