using System;
using System.Collections.Generic;
using TinyDispatcher.SourceGen.Generator.Models;

namespace TinyDispatcher.SourceGen.Generator.Generation.Emitters.Pipelines;

internal static class PipelineSourceWriter
{
    public static string Write(PipelinePlan plan)
    {
        var w = new CodeWriter();

        WriteFileHeader(w);
        WritePipelines(w, plan);
        WriteContribution(w, plan);

        w.EnsureAllBlocksClosed();
        return w.ToString();
    }

    private static void WriteFileHeader(CodeWriter w)
    {
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("using System;");
        w.Line("using System.Threading;");
        w.Line("using System.Threading.Tasks;");
        w.Line("using Microsoft.Extensions.DependencyInjection;");
        w.Line("using Microsoft.Extensions.DependencyInjection.Extensions;");
        w.Line();
    }

    private static void WritePipelines(CodeWriter w, PipelinePlan plan)
    {
        w.BeginBlock($"namespace {plan.GeneratedNamespace}");
        WritePipelineClasses(w, plan);
        w.EndBlock(); // namespace

        w.Line();
    }

    private static void WritePipelineClasses(CodeWriter w, PipelinePlan plan)
    {
        WriteGlobalPipeline(w, plan);
        WritePolicyPipelines(w, plan);
        WritePerCommandPipelines(w, plan);
    }

    private static void WriteGlobalPipeline(CodeWriter w, PipelinePlan plan)
    {
        var globalPipeline = plan.GlobalPipeline;

        if (globalPipeline is null)
        {
            return;
        }

        WritePipeline(w, plan, globalPipeline);
    }

    private static void WritePolicyPipelines(CodeWriter w, PipelinePlan plan)
    {
        for (var i = 0; i < plan.PolicyPipelines.Length; i++)
        {
            WritePipeline(w, plan, plan.PolicyPipelines[i]);
        }
    }

    private static void WritePerCommandPipelines(CodeWriter w, PipelinePlan plan)
    {
        for (var i = 0; i < plan.PerCommandPipelines.Length; i++)
        {
            WritePipeline(w, plan, plan.PerCommandPipelines[i]);
        }
    }

    private static void WritePipeline(CodeWriter w, PipelinePlan plan, PipelineDefinition def)
    {
        var core = plan.CoreFqn;
        var ctx = plan.ContextFqn;

        var commandType = GetPipelineCommandType(def);
        var middlewares = GetDistinctMiddlewares(def);

        WritePipelineHeader(w, core, ctx, def);
        WriteMiddlewareFields(w, ctx, commandType, middlewares);
        WriteRuntimeClass(w, plan, def, commandType);
        w.Line();

        WriteCtor(w, plan, def, commandType, middlewares);
        WriteExecute(w, plan, def);

        w.EndBlock(); // class body
        w.Line();
    }

    private static void WritePipelineHeader(CodeWriter w, string core, string ctx, PipelineDefinition def)
    {
        if (def.IsOpenGeneric)
        {
            WriteOpenGenericPipelineHeader(w, core, ctx, def);
            return;
        }

        WriteClosedPipelineHeader(w, core, ctx, def);
    }

    private static void WriteOpenGenericPipelineHeader(CodeWriter w, string core, string ctx, PipelineDefinition def)
    {
        w.Line(
            $"internal sealed class {def.ClassName}<TCommand> : " +
            $"{core}.ICommandPipeline<TCommand, {ctx}>");
        w.Line($"  where TCommand : {core}.ICommand");
        w.BeginAnonymousBlock(string.Empty);
    }

    private static void WriteClosedPipelineHeader(CodeWriter w, string core, string ctx, PipelineDefinition def)
    {
        w.BeginBlock(
            $"internal sealed class {def.ClassName} : " +
            $"{core}.ICommandPipeline<{def.CommandType}, {ctx}>");
    }

    private static void WriteMiddlewareFields(CodeWriter w, string ctx, string commandType, MiddlewareRef[] middlewares)
    {
        for (var i = 0; i < middlewares.Length; i++)
        {
            var middleware = middlewares[i];
            var fieldType = PipelineTypeNames.CloseMiddleware(middleware, commandType, ctx);
            var fieldName = PipelineNameFactory.FieldName(middleware);

            w.Line($"private readonly {fieldType} {fieldName};");
        }

        w.Line();
    }

    private static MiddlewareRef[] GetDistinctMiddlewares(PipelineDefinition def)
    {
        var middlewares = new List<MiddlewareRef>(def.Steps.Length);

        for (var i = 0; i < def.Steps.Length; i++)
        {
            middlewares.Add(def.Steps[i].Middleware);
        }

        return PipelineMiddlewareSets.DistinctByOpenTypeAndArity(middlewares);
    }

    private static string GetPipelineCommandType(PipelineDefinition def)
    {
        if (def.IsOpenGeneric)
        {
            return "TCommand";
        }

        return def.CommandType;
    }

    private static void WriteRuntimeClass(CodeWriter w, PipelinePlan plan, PipelineDefinition def, string cmdType)
    {
        var core = plan.CoreFqn;
        var ctx = plan.ContextFqn;

        var pipelineType = GetRuntimePipelineType(def);
        var handlerType = GetHandlerType(core, ctx, def);

        w.BeginBlock($"private sealed class Runtime : {core}.Pipeline.ICommandPipelineRuntime<{cmdType}, {ctx}>");
        w.Line($"private readonly {pipelineType} _pipeline;");
        w.Line($"private readonly {handlerType} _handler;");
        w.Line("private int _index;");
        w.Line();

        w.BeginBlock($"public Runtime({pipelineType} pipeline, {handlerType} handler)");
        w.Line("_pipeline = pipeline ?? throw new ArgumentNullException(nameof(pipeline));");
        w.Line("_handler = handler ?? throw new ArgumentNullException(nameof(handler));");
        w.Line("_index = 0;");
        w.EndBlock();
        w.Line();

        // Entry point used by ExecuteAsync
        w.BeginBlock($"public ValueTask StartAsync({cmdType} command, {ctx} ctxValue, CancellationToken ct)");
        w.Line("return NextAsyncInternal(command, ctxValue, ct);");
        w.EndBlock();
        w.Line();

        w.BeginBlock($"private ValueTask NextAsyncInternal({cmdType} command, {ctx} ctxValue, CancellationToken ct)");
        w.BeginBlock("switch (_index++)");

        for (var i = 0; i < def.Steps.Length; i++)
        {
            var mw = def.Steps[i].Middleware;
            w.Line($"case {i}: return _pipeline.{PipelineNameFactory.FieldName(mw)}.InvokeAsync(command, ctxValue, this, ct);");
        }

        w.Line("default: return new ValueTask(_handler.HandleAsync(command, ctxValue, ct));");
        w.EndBlock(); // switch
        w.EndBlock(); // method
        w.Line();

        // Explicit interface implementation
        w.BeginBlock(
            $"ValueTask {core}.Pipeline.ICommandPipelineRuntime<{cmdType}, {ctx}>.NextAsync({cmdType} command, {ctx} ctxValue, CancellationToken ct)");
        w.Line("return NextAsyncInternal(command, ctxValue, ct);");
        w.EndBlock();

        w.EndBlock(); // class Runtime
    }

    private static string GetRuntimePipelineType(PipelineDefinition def)
    {
        if (def.IsOpenGeneric)
        {
            return $"{def.ClassName}<TCommand>";
        }

        return def.ClassName;
    }

    private static string GetHandlerType(string core, string ctx, PipelineDefinition def)
    {
        if (def.IsOpenGeneric)
        {
            return $"{core}.ICommandHandler<TCommand, {ctx}>";
        }

        return $"{core}.ICommandHandler<{def.CommandType}, {ctx}>";
    }

    private static void WriteCtor(CodeWriter w, PipelinePlan plan, PipelineDefinition def, string cmdType, MiddlewareRef[] middlewares)
    {
        var ctx = plan.ContextFqn;

        w.Line($"public {def.ClassName}(");
        for (var i = 0; i < middlewares.Length; i++)
        {
            var middleware = middlewares[i];
            var parameterType = PipelineTypeNames.CloseMiddleware(middleware, cmdType, ctx);
            var parameterName = PipelineNameFactory.CtorParamName(middleware);
            var separator = GetConstructorParameterSeparator(i, middlewares.Length);

            w.Line($"  {parameterType} {parameterName}{separator}");
        }
        w.Line(")");
        w.BeginAnonymousBlock(string.Empty);

        for (var i = 0; i < middlewares.Length; i++)
        {
            var middleware = middlewares[i];
            var fieldName = PipelineNameFactory.FieldName(middleware);
            var parameterName = PipelineNameFactory.CtorParamName(middleware);

            w.Line($"{fieldName} = {parameterName};");
        }

        w.EndBlock();
        w.Line();
    }

    private static string GetConstructorParameterSeparator(int index, int count)
    {
        var isLastParameter = index == count - 1;

        if (isLastParameter)
        {
            return string.Empty;
        }

        return ",";
    }

    private static void WriteExecute(CodeWriter w, PipelinePlan plan, PipelineDefinition def)
    {
        var core = plan.CoreFqn;
        var ctx = plan.ContextFqn;

        var handlerType = GetHandlerType(core, ctx, def);
        var cmdSig = GetPipelineCommandType(def);

        w.BeginBlock($"public ValueTask ExecuteAsync({cmdSig} command, {ctx} ctxValue, {handlerType} handler)");
        w.Line("return ExecuteAsync(command, ctxValue, handler, default);");
        w.EndBlock();
        w.Line();

        w.BeginBlock($"public ValueTask ExecuteAsync({cmdSig} command, {ctx} ctxValue, {handlerType} handler, CancellationToken ct)");
        w.Line("if (command is null)");
        w.BeginAnonymousBlock(string.Empty);
        w.Line("throw new ArgumentNullException(nameof(command));");
        w.EndBlock();
        w.Line();
        w.Line("if (handler is null)");
        w.BeginAnonymousBlock(string.Empty);
        w.Line("throw new ArgumentNullException(nameof(handler));");
        w.EndBlock();
        w.Line();
        w.Line("var runtime = new Runtime(this, handler);");
        w.Line("return runtime.StartAsync(command, ctxValue, ct);");
        w.EndBlock();
        w.Line();
    }

    private static void WriteContribution(CodeWriter w, PipelinePlan plan)
    {
        w.BeginBlock($"namespace {plan.GeneratedNamespace}");
        w.BeginBlock("internal static partial class ThisAssemblyContribution");
        w.BeginBlock("static partial void AddGeneratedPipelines(IServiceCollection services)");
        w.Line("if (services is null)");
        w.BeginAnonymousBlock(string.Empty);
        w.Line("throw new ArgumentNullException(nameof(services));");
        w.EndBlock();
        w.Line();

        if (plan.OpenGenericMiddlewareRegistrations.Length > 0)
        {
            w.Line("// Middleware open-generic registrations (required for generated pipelines ctor injection)");
            for (var i = 0; i < plan.OpenGenericMiddlewareRegistrations.Length; i++)
            {
                w.Line($"services.TryAddTransient(typeof({plan.OpenGenericMiddlewareRegistrations[i].TypeofExpression}));");
            }

            w.Line();
        }

        for (var i = 0; i < plan.ServiceRegistrations.Length; i++)
        {
            var r = plan.ServiceRegistrations[i];
            w.Line($"services.AddScoped<{r.ServiceTypeExpression}, {r.ImplementationTypeExpression}>();");
        }

        w.EndBlock(); // method
        w.EndBlock(); // class
        w.EndBlock(); // namespace
    }
}

