// TinyDispatcher.SourceGen/Emitters/ModuleInitializer/ModuleInitializerSourceWriter.cs

#nullable enable

using System;
using TinyDispatcher.SourceGen.Emitters.Pipelines;

namespace TinyDispatcher.SourceGen.Emitters.ModuleInitializer;

internal static class ModuleInitializerSourceWriter
{
    public static string Write(ModuleInitializerPlan plan)
    {
        if (plan is null) throw new ArgumentNullException(nameof(plan));

        var w = new CodeWriter(capacity: 2_048);

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("using System.Runtime.CompilerServices;");
        w.Line("using Microsoft.Extensions.DependencyInjection;");
        w.Line();

        w.BeginBlock($"namespace {plan.GeneratedNamespace}");
        w.BeginBlock("internal static class DispatcherModuleInitializer");
        w.BeginBlock("[ModuleInitializer] internal static void Init()");

        w.Line("// Contribute this assembly's pipeline + handler DI registrations");
        w.Line($"global::{plan.CoreNamespace}.DispatcherPipelineBootstrap.AddContribution(");
        w.Line($"  services => global::{plan.GeneratedNamespace}.ThisAssemblyPipelineContribution.Add(services));");

        w.EndBlock(); // Init
        w.EndBlock(); // class
        w.EndBlock(); // namespace

        w.EnsureAllBlocksClosed();
        return w.ToString();
    }
}
