using TinyDispatcher.SourceGen.Emitters;

namespace TinyDispatcher.SourceGen.Emitters.Handlers;

internal sealed class HandlerRegistrationsSourceWriter
{
    public string Write(HandlerRegistrationsPlan plan)
    {
        var w = new CodeWriter();

        if (!plan.IsEnabled)
        {
            WriteEmpty(w, plan.Namespace);
            w.EnsureAllBlocksClosed();
            return w.ToString();
        }

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("using System;");
        w.Line("using Microsoft.Extensions.DependencyInjection;");
        w.Line();

        w.BeginBlock($"namespace {plan.Namespace}");
        w.BeginBlock("internal static partial class ThisAssemblyPipelineContribution");
        w.BeginBlock("static partial void AddGeneratedHandlers(IServiceCollection services)");

        w.Line("if (services is null) throw new ArgumentNullException(nameof(services));");
        w.Line();

        // Commands: ICommandHandler<TCommand, TContext> -> Handler
        for (int i = 0; i < plan.Commands.Length; i++)
        {
            var c = plan.Commands[i];
            w.Line(
                $"services.AddTransient(typeof(global::TinyDispatcher.ICommandHandler<{c.MessageTypeFqn}, {plan.CommandContextFqn}>), typeof({c.HandlerTypeFqn}));");
        }

        if (plan.ShouldInsertBlankLineBetweenCommandAndQueryBlocks)
            w.Line();

        // Queries: IQueryHandler<TQuery, TResult> -> Handler
        for (int i = 0; i < plan.Queries.Length; i++)
        {
            var q = plan.Queries[i];
            w.Line(
                $"services.AddTransient(typeof(global::TinyDispatcher.IQueryHandler<{q.QueryTypeFqn}, {q.ResultTypeFqn}>), typeof({q.HandlerTypeFqn}));");
        }

        w.EndBlock(); // AddGeneratedHandlers
        w.EndBlock(); // ThisAssemblyPipelineContribution
        w.EndBlock(); // namespace

        w.EnsureAllBlocksClosed();
        return w.ToString();
    }

    private static void WriteEmpty(CodeWriter w, string ns)
    {
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("using Microsoft.Extensions.DependencyInjection;");
        w.Line();

        w.BeginBlock($"namespace {ns}");
        w.BeginBlock("internal static partial class ThisAssemblyPipelineContribution");
        w.Line("static partial void AddGeneratedHandlers(IServiceCollection services) { }");
        w.EndBlock();
        w.EndBlock();
    }
}